### ISSUE TITLE
Some questions regarding the tutorial

### ISSUE THREAD

**Issue by stephenllh** [bodywork-ml/bodywork-core#119]
I am following your tutorial. It is amazing, but I have a few questions.

In the part 1 of the tutorial, when I wanted to manually test the deployed prediction endpoint, I typed this in my terminal:

`curl http://CLUSTER_IP/pipelines/time-to-dispatch--serve-model/api/v0.1/time_to_dispatch`

The CLUSTER_IP is not defined and it gives an error. So, I understand that the CLUSTER_IP might not be accessible if I use minikube, but would it be a problem when I deploy it on AWS?

And also, where does the `time-to-dispatch--serve-model` in the endpoint come from?

**Comment by AlexIoannides** [comment]
Hi Stephen, thanks for the positive feedback!

It sounds like I might have been unclear. By `CLUSTER_IP`, I meant, "_insert the IP address or URL for your cluster here._" You can find this for Minikube by running the following command,

```shell
$ minikube profile list

|----------|-----------|---------|--------------|------|----------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version  | Status  | Nodes |
|----------|-----------|---------|--------------|------|----------|---------|-------|
| minikube | hyperkit  | docker  | 192.168.64.6 | 8443 | v1.17.17 | Running |     1 |
|----------|-----------|---------|--------------|------|----------|---------|-------|
```

If you had a cluster on AWS (or Azure, or GCP), then you can retrieve the IP/URL for the load balancer that is forwarding traffic to the ingress controller, by running the following command,

```shell
$ kubectl -n ingress-nginx get service ingress-nginx-controller

NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP                                                                     PORT(S)                      AGE
ingress-nginx-controller   LoadBalancer   10.100.61.30   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.elb.eu-west-2.amazonaws.com   80:30512/TCP,443:30282/TCP   163d
```

You'd use the `EXTERNAL_IP`. This requires you to have kubectl installed on your local machine and to have installed the NGINX ingress controller on your cluster. If this doesn't mean anything to you or you'd like more info, then head to our docs [here](https://bodywork.readthedocs.io/en/latest/kubernetes/#configuring-ingress). If you need more help, then drop a question onto our [Discussions board](https://github.com/bodywork-ml/bodywork-core/discussions) or drop us an e-mail 🙂
