### ISSUE TITLE
Implement Bodywork Deployment Delete

### ISSUE THREAD

**Issue by Marios85** [bodywork-ml/bodywork-core#120]
"As an ML Engineer I want to be able to delete a deployment"

Implement a CLI command to delete a namespace (effectively `kubectl delete ns project-name`)

N.B. We need to update the docs to make it clear that if a user has specified a specific namespace to deploy to in the Bodywork YAML then this will be the name they have to give to the CLI or they will need to specify this as a parameter (would make the usage more consistent).

**Comment by AlexIoannides** [comment]
```
if namespace has multiple_project_services:
    delete deployment_services
else:
    delete namespace
```
