### ISSUE TITLE
Make local workflow controller the default (and only) option for the CLI

### ISSUE THREAD

**Issue by AlexIoannides** [bodywork-ml/bodywork-core#133]
It makes no sense for the workflow controller to be run anywhere other than locally - e.g. even if running on a CI/CD box, it needs to run locally. This should become the default option and we should remove the asynchronous option from the CLI, but not from the internal `k8s` sub-module, we we'll need this for the REST API.

**Comment by Marios85** [comment]
Updated to keeping the option to deploy workflows remotely but just setting the default to be the local workflow i.e. You will need to set a flag for async and not for local.
