### ISSUE TITLE
Make Secrets and Their Associated Groups Clearer

### ISSUE THREAD

**Issue by AlexIoannides** [bodywork-ml/bodywork-core#135]
Currently, a secret in group `dev` with name `api-password` will be given a k8s resource name of `dev-api-password`, which makes it hard to figure-out what group it belongs to, if you've forgotten what groups are in existence and you have other k8s secrets floating around. Maybe, this would be easier if the secret name would be something like `dev--api-password`?

Additionally, it would be useful to have a command along the lines of `bodywork secret display groups`, that lists the secrets groups in existence by looking at the labels of all secrets.

**Comment by Marios85** [comment]
This task is just to make the display of secrets clearer so that the group name is separated from the secret name and it is clear to see which is which.
