### ISSUE TITLE
bodywork get deployment - GitBranch Shows Stage Name Instead of Git Branch. 

### ISSUE THREAD

**Issue by Marios85** [bodywork-ml/bodywork-core#169]
When viewing a deployment using `bodywork get deployment` the stage name is incorrectly shown for GitBranch. 

See Attached email for detail.
[Email - Marios Ioannides - Outlook.pdf](https://github.com/bodywork-ml/bodywork-core/files/8529769/Email.-.Marios.Ioannides.-.Outlook.pdf)

**Comment by AlexIoannides** [comment]
Closed by #173
