### ISSUE TITLE
How we can configure Multiple workflow in same Git Repo

### ISSUE THREAD

**Issue by Riki-1mg** [bodywork-ml/bodywork-core#44]
I am exploring Bodywork for Last few days.
 We have multiple models running in Production. I want to configure multiple model workflow in same git repo without changing branch. Can you please help me ?

**Comment by AlexIoannides** [comment]
For sure - it'd be our pleasure.

I'd need to know a bit more about your current model workflows - what they do and what you're trying to achieve.

Would it  be okay to move the conversation over to the [Discussions board](https://github.com/bodywork-ml/bodywork-core/discussions), so it's available for others who might be in a similar situation? if you'd like to keep it confidential, then 
you can drop me an e-mail at info@bodyworkml.com and we can go from there.
