### ISSUE TITLE
Update deployment template projects for v0.3.0 release

### ISSUE THREAD

**Issue by AlexIoannides** [bodywork-ml/bodywork-core#50]
The `config.ini` files in each of the deployment templates will require the `INGRESS` parameter to be set for all service stages, in order to be compatible with Bodywork v0.3.0.

This is also a good opportunity to add a license (MIT for these?), version file and possibly a CHANGELOG.md file.

**Comment by AlexIoannides** [comment]
PR have been created for each template project:

- [batch job](https://github.com/bodywork-ml/bodywork-batch-job-project/pull/1)
- [serve model](https://github.com/bodywork-ml/bodywork-serve-model-project/pull/1)
- [ML pipeline](https://github.com/bodywork-ml/bodywork-ml-pipeline-project/pull/1)
- [dashboard](https://github.com/bodywork-ml/bodywork-ml-dashboard-project/pull/1)
- [Jupyter pipelines](https://github.com/bodywork-ml/bodywork-ml-dashboard-project/pull/1)

@Marios85 I don't think we **need** an official review for these (your time is better spend elsewhere), but they're here for completeness.

**Comment by Marios85** [comment]
I agree 🙂

**Comment by AlexIoannides** [comment]
I've checked all of these and they are now all working with v0.3.0 using the info in the READMEs.

I'll need to make some minor tweaks when #39 is merged, but otherwise we are good to go.
